Cargo.lock
Cargo.toml
src/dfxvm/install.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfx.rs

The tempdir crate is deprecated: https://github.com/rust-lang-deprecated/tempdir
It also depends on version 0.5.3 of the remove_dir_all crate, which has a security warning
Replaced the dependency with the [tempfile](https://docs.rs/tempfile/latest/tempfile/) crate.
Intended to eliminate this dependabot warning: https://github.com/dfinity/dfxvm/security/dependabot/1
Covered by existing tests

chore: replace deprecated dependency: tempdir -> tempfile

---

.github/workflows/test.yml
tests/suite/common/executable.rs
tests/suite/common/mod.rs
tests/suite/common/temp_home_dir.rs

I have noticed tests failing like this, but more often recently:
```
Failed to spawn HOME="/tmp/dfxvm-integration-tests-homeUbf1FB" 
"/tmp/dfxvm-integration-tests-homeUbf1FB/dfx": 
Text file busy (os error 26)
```
This PR makes two changes:
- don't re-create a copy of dfxvm with a given name 
- when creating any executable, try to execute it until anything other than os error 26 happens
I ran tests with three branches, modified to run the tests without an open PR and to set RUST_BACKTRACE=1:
- same as main ([workflow](url)): 8 failures out of 20 attempts
- do not re-create dfxvm binaries ([workflow](url)): 15 failures out of 20 attempts
- this branch ([workflow](https://github.com/dfinity/dfxvm/actions/runs/7039399141)): 0 failures out of 20 attempts

fix: tests failing with "text file busy"

---

.github/workflows/test.yml
tests/suite/common/mod.rs
tests/suite/common/project_dirs.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfxvm/install.rs
tests/suite/dispatch.rs

On Linux, if XDG_DATA_HOME is set, dfxvm should store dfx binaries relative to it.  This PR adds tests that verify that this is so.
It also isolates commands run by tests from the host environment by clearing the Command's environment and setting a limited PATH.
This also removed the dependency from the test suite on the [directories](https://docs.rs/directories/latest/directories/) crate, instead having the test code express the expected paths directly.
Added tests

test:  verify expected behavior if XDG_DATA_HOME is set

---

README.md
src/installation/env.rs

Adds an acknowledgements section to the readme, and an attribution for code/files derived/copied/modified from rustup.
Also adds a copyright notice, and fixes a typo in the link to the contributing doc.

docs: copyright and acknowledgements

---

src/dfxvm_init/cli.rs
src/dfxvm_init/initialize.rs
src/dfxvm_init/plan.rs
src/dfxvm_init/ui/customize.rs
src/dfxvm_init/ui/display.rs

Moves the customizable parts of a Plan into a new PlanOptions struct, primarily so that the CLI layer can initialize them from command-line options.
For further context, see https://github.com/dfinity/dfxvm/pull/35
Refactor covered by existing tests.

refactor: PlanOptions

---

CHANGELOG.md
docs/cli-reference/dfxvm-init/dfxvm-init.md
src/dfxvm_init/cli.rs
src/dfxvm_init/initialize.rs
src/dfxvm_init/plan.rs
src/dfxvm_init/ui/customize.rs
src/dfxvm_init/ui/display.rs
src/error/dfxvm_init.rs
src/error/fs.rs
src/fs.rs
src/installation.rs
src/installation/profile.rs
src/installation/shell.rs
tests/suite/common/release_server.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfxvm_init.rs

dfxvm-init now updates profile scripts for posix (.profile), bash, and zsh to add the dfxvm bin directory to the PATH.
Fixes https://dfinity.atlassian.net/browse/SDK-1275
Added tests and tested locally.

feat: init mode alters profile scripts to update PATH

---

src/dfxvm/install.rs
src/download.rs
src/error.rs
src/error/dfxvm/install.rs
src/error/download.rs
src/main.rs

`self update` will need to download files, so this PR moves the download_file method to its own file.
Covered by CI

refactor: download file

---

src/cli.rs
src/dfx.rs
src/dfxvm/cli.rs
src/dfxvm/default.rs
src/dfxvm/install.rs
src/dfxvm/list.rs
src/dfxvm/self_uninstall.rs
src/dfxvm/self_update.rs
src/dfxvm/uninstall.rs
src/dfxvm/update.rs
src/dfxvm_init/cli.rs
src/dfxvm_init/initialize.rs
src/error/cli.rs
src/error/dfx.rs
src/error/dfxvm.rs
src/error/dfxvm/default.rs
src/error/dfxvm/install.rs
src/error/dfxvm_init.rs

All of the dfxvm commands need the `Locations` object.  `self update` needs it a little higher in the call stack, in order to delete a binary.
This PR makes it so there is only one place that calls `Locations::new()`, and it's higher in the call stack.  This also means there are fewer places that can return `NoHomeDirectory` as an error.
Covered by CI

refactor: construct Locations in one place

---

CHANGELOG.md
docs/cli-reference/dfxvm/dfxvm-self-update.md
src/dfx.rs
src/dfxvm.rs
src/dfxvm/cli.rs
src/dfxvm/self_update.rs
src/dfxvm_init/cli.rs
src/dfxvm_init/plan.rs
src/dist_manifest.rs
src/error/dfx.rs
src/error/dfxvm.rs
src/error/dfxvm/self_update.rs
src/error/dfxvm_init.rs
src/locations.rs
src/main.rs
src/settings.rs
tests/suite/common/file_contents.rs
tests/suite/common/mod.rs
tests/suite/common/release_asset.rs
tests/suite/common/release_server.rs
tests/suite/common/settings.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfxvm/self_update.rs

Adds the `dfxvm self update` command.
Fixes https://dfinity.atlassian.net/browse/SDK-1272
Added tests
Tested locally by:
- change Cargo.toml version and rebuild
- run `dfxvm self update`
- it downloads and extracts the tarball, but fails when trying to call the contained binary with `dfxvm-init --self-replace`, since the older releases obviously don't support this functionality
- copied the dfxvm binary over the dfxvm-init-self-update binary in the bin directory
- called `dfxvm-init-self-update --self-replace` in the bin directory

feat: self update

---

docs/cli-reference/index.md

Fixes internal linking in the CLI reference index file.

docs: update internal links in CLI reference index file

---

.github/workflows/audit.yml

This should have been `audit:required` to match the other required statuses like `fmt:required` and `test:required`

fix: make audit:required status name consistent with others

---

.github/workflows/test.yml

This is to fix this audit warning seen at https://github.com/dfinity/dfxvm/actions/runs/7697288174:
>    Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chore: update to actions/cache@v4

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deny.toml

Avoids this error on install (seen with WSL):
```
./dfxvm-init: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
This also sets unlicensed crates to be allowed, needed for https://docs.rs/ring/0.17.7/ring/.  Compare to https://github.com/dfinity/sdk/blob/master/deny.toml#L7
Fixes https://dfinity.atlassian.net/browse/SDK-1357
An earlier commit of this PR set `pr-run-mode` to `upload`.  I downloaded the build artifacts from https://github.com/dfinity/dfxvm/actions/runs/7712551789 and ran them under wsl.  No missing .so errors.

fix: static-link ssl

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deny.toml

- removes the openssl dependency altogether
- add a named exclusion for `ring` rather than allowing any unlicensed crates

chore: remove openssl dependency, add license exclusion for ring

---

.github/workflows/test.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
docs/cli-reference/dfxvm/dfxvm-self-uninstall.md
src/dfxvm/cli.rs
src/dfxvm/self_uninstall.rs
src/error/dfxvm.rs
src/error/dfxvm/self_uninstall.rs
src/installation.rs
src/installation/shell.rs
src/locations.rs
tests/suite/common/file_contents.rs
tests/suite/common/release_asset.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfxvm/self_uninstall.rs
tests/suite/dfxvm_init.rs

Adds the `self uninstall` command.
Fixes https://dfinity.atlassian.net/browse/SDK-1273
Note to reviewers: the only thing I'm not super stoked about is the profile cleanup.  Specifically, it will find a line like `# . <data-local-dir>/env` and change it to `# `.  On the other hand, this is what rustup does, and I suppose it works well enough for them.  The same kind of thing comes up during install: A commented-out line in a profile script will cause dfxvm-init not to add the source command to the profile script.
Added a test

feat: self uninstall

---

CHANGELOG.md
src/dfxvm/self_uninstall.rs
src/dfxvm_init/initialize.rs
src/dfxvm_init/plan.rs
src/dfxvm_init/ui.rs
src/dfxvm_init/ui/customize.rs
src/dfxvm_init/ui/deletion_strategy.rs
src/dfxvm_init/ui/display.rs
src/error/dfxvm_init.rs
src/locations.rs
tests/suite/common/mod.rs
tests/suite/common/paths.rs
tests/suite/common/temp_home_dir.rs
tests/suite/dfxvm/self_uninstall.rs
tests/suite/dfxvm_init.rs

This PR makes `dfxvm-init` delete dfx wherever it is found on the PATH, except for dfxvm's bin directory.   This is necessary because even though the env file prepends the dfxvm bin directory to the PATH, /usr/local/bin ends up before it.
`dfxvm-init` now also deletes ~/.cache/dfinity/uninstall.sh, and `dfxvm self uninstall` deletes ~/.cache/dfinity entirely.
Fixes https://dfinity.atlassian.net/browse/SDK-1276
Added tests, and tested the `sudo rm` flow directly.

feat: clean up previous dfx installation

---

README.md

This just moves the links to the bottom and alphabetizes them

docs: move links to end of file

---

CHANGELOG.md
docs/settings-json-schema.json
src/dfxvm/install.rs
src/settings.rs
tests/suite/common/file_contents.rs
tests/suite/common/mod.rs
tests/suite/common/release_asset.rs
tests/suite/common/release_server.rs
tests/suite/common/target.rs

Download the new release tarballs, which store the dfx binary in a subdirectory of the same name as the archive.  This matches the structure of the release archives that cargo-dist makes, and is more consistent with release tarballs in general (though there are no strict rules).
Fixes https://dfinity.atlassian.net/browse/SDK-1360
Installed dfx 0..5.2, 0.9.3, 0.16.0, and 0.16.1-cargodist.4 (actually created with cargo-dist) on OSX and WSL.

feat: download cargo-dist-style release tarballs

---

CHANGELOG.md
src/dfx.rs
tests/suite/dfx.rs

If allowed to execute under dfxvm, `dfx upgrade` would overwrite the dfx executable in the versions directory.
Fixes https://dfinity.atlassian.net/browse/SDK-1361
Added a test and ran locally

fix: disable dfx upgrade

---

CHANGELOG.md
docs/cli-reference/dfx/dfx.md
src/dfx.rs
src/env.rs
tests/suite/common/paths.rs
tests/suite/dfx.rs
tests/suite/dfxvm_init.rs

When proxying to dfx:
- set DFX_VERSION so that dfx doesn't in turn forward to something else
- prepend the dfx bin path to PATH so that any calls to dfx in package.json or build scripts will go to the right place
All dfx binaries to date look at DFX_VERSION and the "dfx" field in dfx json.  If these indicate to use a different version of dfx, they forward to that version instead.  By setting DFX_VERSION, we ensure that dfx won't forward to a different version.
Previous installed versions of dfx were installed to /usr/local/bin.  While it's likely that the dfxvm bin directory is on the path, adding the dfx version bin directory to the path will ensure that any calls to dfx go to the right version.
Fixes https://dfinity.atlassian.net/browse/SDK-1362
Added a test.   Also:
Before:
```
$ echo …
```

fix: set DFX_VERSION and add dfx bin path to PATH when calling dfx proxy

---

README.md

Now that dfxvm has been released, the install script is available at the usual place.

docs: use release install url

---

Cargo.lock

For RUSTSEC-2024-0332 audit failure

chore: update h2 dependency

---

Cargo.lock
Cargo.toml
deny.toml

Fixed the audit check by 
1. updating `reqwest` to `0.12.9`, `url` to `2.5` to upgrade from the vulnerable `idna` from `0.5` to `1.0.3`.
2. updating the Cargo.lock file
Fixed the license by 
1. allowing `Unicode-3.0` license, as the new `idna 1.0.3` introduces a bunch of dependencies which are , for example `icu_normalizer`, `icu_locid_transform_data` etc. 
2. The [dfinity/sdk](https://github.com/dfinity/sdk/blob/master/deny.toml#L20) repo also allows this license type.
Todo:
1. replace the unmaintained `instant` crate in the future according to [this report](https://github.com/dfinity/dfxvm/actions/runs/12292326908).
Fixes # (issue)
Covered by the existing tests and checks.

fix: update reqwest and url to fix the cargo audit error.

---

CHANGELOG.md
docs/cli-reference/dfxvm/dfxvm-list.mdx
src/dfxvm.rs
src/dfxvm/cli.rs
src/dfxvm/list.rs
src/dfxvm/manifest.rs
src/dfxvm/update.rs
src/error/dfxvm.rs
tests/suite/dfxvm/list.rs

`dfxvm --list` now supports listing the available dfx versions.
- `--available`: List the available versions.
- `--limit`:The maximum number of available versions to list in reverse chronological order, with default value `10`.
Fixes # (issue)
[SDK-1883](https://dfinity.atlassian.net/browse/SDK-1883)
1. Manually tested
2. Test added.
[SDK-1883]: https://dfinity.atlassian.net/browse/SDK-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: `dfxvm --list` now supports listing the remote available dfx versions.

---

CONTRIBUTING.md

chore: update release document.
